apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-monitoring
  name: prometheus
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: prometheus
