apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: kube-system
  labels:
    app: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      serviceAccountName: cert-manager
      tolerations: []
      nodeSelector: {}
      containers:
      - name: cert-manager
        image: quay.io/jetstack/cert-manager-controller:v0.4.0
        args:
        - --issuer-ambient-credentials=true
        - --cluster-issuer-ambient-credentials=true
        - --default-acme-issuer-challenge-type=dns01
        - --default-acme-issuer-dns01-provider-name=aws-route53
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=$(POD_NAMESPACE)
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http-metrics
          containerPort: 9402
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 32Mi
