apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: kube-system
  labels:
    app: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager
  labels:
    app: cert-manager
rules:
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificates
  - issuers
  - clusterissuers
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - secrets
  - events
  - endpoints
  - services
  - pods
  - configmaps
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager
  labels:
    app: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager
subjects:
- name: cert-manager
  namespace: kube-system
  kind: ServiceAccount
