apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: monitoring
  labels:
    app: cert-manager
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: cert-manager
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: http-metrics
    path: metrics
    interval: 30s
