apiVersion: v1
kind: Service
metadata:
  name: cert-manager
  namespace: kube-system
  labels:
    app: cert-manager
spec:
  clusterIP: None
  selector:
    app: cert-manager
  ports:
  - name: http-metrics
    targetPort: http-metrics
    port: 9402
